### ISSUE TITLE
Open lists have lost spacing between items

### ISSUE THREAD

**Issue by tuukkamustonen** [readthedocs/sphinx_rtd_theme#705]
### Problem

With:

```
- A bullet list

  Second paragraph.

- Another item

  Second paragraph.
```

Renders as:

![image](https://user-images.githubusercontent.com/94327/50098148-035cc380-0224-11e9-89e0-8559cf58cfb5.png)

There should be margin after last paragraph, but looks like it's missing.

This was discussed/fixed in https://github.com/rtfd/sphinx_rtd_theme/issues/590 that should be in now, but it doesn't seem to work?

### Environment Info

- Python Version: `2.7`
- Sphinx Version: `1.8.2`
- RTD Theme Version: `0.4.2`

**Comment by domdfcoding** [comment]
This issue is still present as of 2020 in version 0.4.3

**Comment by polyzen** [comment]
Try 0.5.0rc1, this should be resolved.

**Comment by jack1142** [comment]
This still happens in 0.5.0rc2 ([link](https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/getting_started.html#user-documentation)):
![image](https://user-images.githubusercontent.com/6032823/83918582-59eff180-a779-11ea-94b4-a9fbcdf6f98f.png)

**Comment by Blendify** [comment]
I just tested using the latest version and this works: 
![image](https://user-images.githubusercontent.com/15183467/111021680-2000eb00-839c-11eb-9535-5559673dd9f8.png)

This also seems to work on the other example given, I also don't see any overrides for css so I assume this is working for everyone.
